DEFAULT_DENSE_LAYER_UNITS = 64
CROSS_ENTROPY_AFTER_SOFTMAX_FUNC = "CROSS_ENTROPY_AFTER_SOFTMAX_FUNC"
CONVOLUTION_SIGNALS_VALID_VALUES = ("max", "avg", "median")
CONVOLUTION_PADDING_VALID_VALUES = ("valid", "same")
